name = "digitaalinen-tuotepassi"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "digitaalinen_tuotepassi"
database_id = "9fc75247-43ec-4fde-a16d-d331ef3b0e66"

[assets]
directory = "./public"
binding = "ASSETS"
